---
- name: upgrade CentOS via yum
  yum: name=* state=latest update_cache=yes
  register: output
  debug: msg="{{ output.stdout }}"
  debug: msg="{{ output.stderr }}"

- name: install common packages
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - libselinux-python
    - sudo
    - ntp
    - ntpdate
    - crontabs
    - strace
    - less
    - vim-enhanced
    - lsof
    - tcpdump

- name: remove awful packages
  yum: name={{item}} state=absent update_cache=yes
  with_items:
    - NetworkManager
    - cups
    - iw
