---
- name: install common packages
  yum:
    name: ['libselinux-python', 'sudo','ntp', 'ntpdate', 'crontabs', 'strace', 'less', 'vim-enhanced', 'lsof', 'tcpdump']
    state: 'present'
    update_cache: yes

- name: upgrade CentOS via yum
  yum:
    name: '*'
    state: 'latest'
    update_cache: yes


- name: remove awful packages
  yum:
    name: ['NetworkManager', 'cups', 'iw']
    state: 'absent'
    update_cache: yes

